#!/bin/bash

export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export HETS_LIB=/opt/hets-lib
export HETS_MAGIC=/opt/hets/lib/hets.magic
export HETS_OWL_TOOLS=/opt/hets/lib/hets-owl-tools
export HETS_APROVE=$HETS_OWL_TOOLS/AProVE.jar
export HETS_ONTODMU=$HETS_OWL_TOOLS/OntoDMU.jar
export PELLET_PATH=/usr/sbin/pellet
exec "/opt/hets/bin/hets-bin" "$@"
